### ISSUE TITLE
Bot didnt trigger on DefiPeak funding/ Money laundering stage

### ISSUE THREAD

**Issue by christian-forta** [venglov/Funding-Laundering-Detector#2]
https://etherscan.io/tx/0x1adb569f1c4538a7f715876a18e560891cfb4e59577be7c9b719dddb335f6da8 - Money Laundering Tx

https://etherscan.io/tx/0x00966dafe1dd77e4599481988ddb9e1ea76c60e49c79c6e94381e95c98ba74ec - Funding Tx

</div></b>

**Comment by venglov** [comment]
Transactions were executed before the bot was deployed

**Comment by christian-forta** [comment]
Vyacheslav, I deployed the bot locally and ran these tx.

**Comment by venglov** [comment]
@christian-forta It looks like it's an optimization mechanism. The bot should collect the database firstly to identify exchanges. So you need to run the range of blocks before the tx. I will verify this hack locally and will let you know.

**Comment by christian-forta** [comment]
Thank you @venglov

**Comment by christian-forta** [comment]
While you are at it, could you pls also check this tx. This is funding via the mulitchain bridge.

**Comment by venglov** [comment]
@christian-forta sure, pls link the tx

**Comment by venglov** [comment]
@christian-forta 
Sorry for the delay, it got a little silly because the bot didn't really trigger and I can't figure out why. It turns out everything is very simple. My bot can't get the number of transactions in the past, when the hack happened, it gets the current number. Therefore, my bot didn't recognize this address as a new one and therefore ignored such a tiny balance increase. However, when I changed the threshold for the number of transactions to determine the new address or not - it immediately recognized the transaction.

<img width="1094" alt="image" src="https://user-images.githubusercontent.com/36051968/207164477-bc50ac7b-e5f5-4f08-a54f-2c35e3f90381.png">

**Comment by venglov** [comment]
@christian-forta, Laundering also works as excepted. :)
<img width="933" alt="image" src="https://user-images.githubusercontent.com/36051968/207166682-53c67626-0beb-4275-9de1-de7b85e357d5.png">
